// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oezbygqihatwwhfntjyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lemJ5Z3FpaGF0d3doZm50anl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MTkwMzEsImV4cCI6MjA1NTA5NTAzMX0.Gc_ZKwznNxu4QuDLKDaLLKzlI6eal3tuEWTmiui2nEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);